app/models.py
from flask_login import UserMixin
from requests import session
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from datetime import datetime
from . import login_manager



@login_manager.user_loader
def load_user(user_id):
  return User.query.get(int(user_id))
class User(db.Model,UserMixin):
  __tablename__='users'
  id = db.Column(db.Integer,primary_key = True)
  email = db.Column(db.String(255),unique = True,index=True)
  pass_secure = db.Column(db.String(255))
  
  @property
  def password(self):
    raise AttributeError('Encrypted')
  
  @password.setter
  def password(self,password):
    self.pass_secure = generate_password_hash(password)
    
  def verify_password(self,password):
    return check_password_hash(self.pass_secure,password)
  
  
class Blog(db.Model,UserMixin):
  __tablename__='blogs'
  id = db.Column(db.Integer,primary_key = True)
  title = db.Column(db.String(30))
  author = db.Column(db.String(25))
  blog_post = db.Column(db.String())
  date_posted = db.Column(db.DateTime,default=datetime.utcnow)
  comments = db.relationship('Comment',backref='blog',lazy='dynamic')

  
  # poster = db.Column(db.LargeBinary)
  
  def save_blog(self):
    db.session.add(self)
    db.session.commit()
    
  def delete(self):
    db.session.delete(self)
    db.session.commit()
    
  @classmethod
  def get_blog(cls, id):
    blogs = Blog.query.filter_by(id=id).all()
    return blogs
  

class Comment(db.Model):
  __tablename__ = 'comments'
  id = db.Column(db.Integer, primary_key=True)
  comment = db.Column(db.String(255))
  blog_id = db.Column(db.Integer,db.ForeignKey('blogs.id',ondelete='SET NULL'),nullable = True) 
  blog_pic = db.Column(db.String(255))
  
  def save_comment(self):
    if self not in db.session:
        db.session.add(self)
        db.session.commit()
  def delete(self):
      db.session.remove(self)
      db.session.commit()

        
  @classmethod
  def get_comments(cls,blog_post):
     comments = Comment.query.filter_by(blog_post=blog_post).all()
     return comments
   
  def __repr__(self):
    return f'Comment {self.comment}'
  
class Subscriber(db.Model):
    __tablename__='subscribers'

    id=db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(20))
    email = db.Column(db.String(255),unique=True,index=True)

    def save_subscriber(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'Subscriber {self.email}'
      

    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SelectField,SubmitField,TextAreaField
from wtforms.validators import DataRequired

class CommentsForm(FlaskForm):
    comment = TextAreaField('Add a comment',validators = [DataRequired()])
    
    submit = SubmitField('Submit')
    
class SubscribeForm(FlaskForm):
    username = StringField('Name',validators = [DataRequired()])
    email = StringField('Email',validators = [DataRequired()])    
    submit = SubmitField('Subscribe')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail




bootstrap = Bootstrap()
db =SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
mail = Mail()

def create_app(confi_name):
  app = Flask(__name__)

  app.config.from_object(config_options[confi_name])
  
  
  bootstrap.init_app(app)
  db.init_app(app)
  login_manager.init_app(app)
  mail.init_app(app)
  
  from .auth import auth as auth_blueprint
  app.register_blueprint(auth_blueprint)
  
  from .main import main as main_blueprint
  app.register_blueprint(main_blueprint)
  
  
  return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,flash
from flask_login import login_required
from . import main
from ..models import Blog,Subscriber
from ..requests import get_random_quote
from ..models import Blog,Comment
from .forms import CommentsForm,SubscribeForm
from ..email import mail_message

@main.route('/')
def index():
    quote = get_random_quote()
    blog_list = Blog.query.order_by(Blog.date_posted.desc()).all()
    return render_template('index.html',quote=quote,blog_list=blog_list)

@main.route('/readmore')
def readmore():
    # # blog = Blog.query.get(blog_id=id)
    # blog_clicked= Blog.query.filter_by(blog_id=id).all()
    return render_template('readmore.html')

@main.route('/about')
def about():
    return render_template('about.html')
@main.route('/comment/<int:blog_id>', methods= ['GET', 'POST'])

def comment(blog_id):
    form = CommentsForm()
    blog = Blog.query.get(blog_id)
    comments = Comment.query.filter_by(blog_id = blog_id).all()
    if form.validate_on_submit():
        comment = form.comment.data
        blog_id = blog_id
        new_comment = Comment(comment=comment, blog_id=blog_id)
        new_comment.save_comment()
        return redirect(url_for('.comment',blog_id=blog_id))
    return render_template('comments.html', form =form, blog = blog,comments=comments)

@main.route('/subscribe',methods = ['POST','GET'])
def subscribe():
    subscribe_form = SubscribeForm()
    if subscribe_form.validate_on_submit():
        email = request.form.get('email')
        username = request.form.get('username')
        new_subscriber = Subscriber(email = email, username = username)
        new_subscriber.save_subscriber()
        mail_message("Hi, Thank you for subscribing","email/subscriber",new_subscriber.email,new_subscriber=new_subscriber)
        flash('Thank you for your subscription')
        return redirect(url_for('main.index'))
    return render_template('subscribe.html',subscribe_form=subscribe_form)

app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
      <div class="profile-text">
          <h2 class="text-center">About Me</h2>
          <p class="p-5">Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.</p>
      </div>
      <div class="social text-center">
        <a href="www.facebook.com"><i class="fa fa-facebook-official" aria-hidden="true"></i></a>
        <a href="www.github.com"><i class="fa fa-github " aria-hidden="true"></i></a>
        <a href="www.twitter.com"><i class="fa fa-twitter" aria-hidden="true"></i></a>
      </div>
    </div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sirwani's</title>
</head>
<body>
  {% block navbar %}
  {% include 'navbar.html' %}
  {% endblock %}
  {% block content %}{% endblock %}


  {% block footer %}
  {% include 'footer.html' %}
  {% endblock %}
  
</body>
</html>

app/templates/comments.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %} 

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3>{{blog.title}}</h3>
  <p>{{blog.blog_post}}</p>
  <h6>Comments</h6>
  {% for comment in comments %}
  <div class="card mt-2">
    <div class="card-body">
      {{comment.comment}}
    </div>
  </div>
  {% endfor %}
</div>
<div class="col-md-6">
  {{wtf.quick_form(form)}}
</div>
</div>

</div>

{% endblock %}

app/templates/footer.html
<footer class="page-footer font-small dark pt-3">
  <div class="footer-copyright text-center py-3">© 2022 Copyright:
    <a href="/">Collins Sirwani</a>
  </div>
</footer>

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center mt-0">
      <p>{{quote.quote}}
      <strong><p>~ {{quote.author}}</p></strong>
    </div>
  </div>
</div>

<div class="container">
<div class="row">
  
  <div class="leftcolumn">
    {% for blog in blog_list %}
    <div class="card">
      <h2>{{blog.title}}</h2>
      <h5>{{blog.date_posted.strftime('%Y-%m-%d')}}</h5>
      <p>{{blog.blog_post | truncate(100)}}<span><a href="">...Read More</a></span></p>
      <div>
        <a href="{{url_for('main.comment',blog_id=blog.id)}}"><button class="btn btn-dark">Comment</button></a>
      </div>
    </div>
    {% endfor %}
   
  </div>
  <div class="rightcolumn">
    <div class="card">
      <h2>Subscribe</h2>
      <p><a href="">subscibe link</a> </p>
    </div>
    <div class="card">
      <h3>Recent Blogs</h3>
      {% for blog in blog_list %}
      <p><a href="{{blog.description}}">{{blog.title}}</a></p><br>
      {% endfor %}
    </div>
  </div>
</div>
</div>
{% endblock %}

app/templates/navbar.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<style>
  .navbar {
  padding:0rem;
  margin-bottom:2rem;
}

.dropdown .dropdown-menu {
  border-radius:0;
 }

@media (min-width: 768px) {  
.dropdown:hover .dropdown-menu {
    display: block;
    margin-top: 0;
  border-radius:0;
 }
}

</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="container">
<nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top text-light">
<div class="collapse navbar-collapse flex-column" id="navbar">
  <ul class="navbar-nav w-100 justify-content-right">
    <li class="nav-item active">
      <a class="nav-link" href="www.facebook.com"><i class="fa fa-facebook-official" style="color: white" aria-hidden="true"></i></a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="www.github.com"><i class="fa fa-github " aria-hidden="true" style="color: white"></i>
      </a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="www.twitter.com"><i class="fa fa-twitter" aria-hidden="true" style="color: white"></i>
      </a>
    </li>
     
    
  </ul>

  <ul class="navbar-nav p-2 w-100 justify-content-center">
    <li class="nav-item active">
      <a class="nav-link" href="#" style="font-size: 50px; color: white !important;">Sirwani</a>
    </li>
     
    
  </ul>

  <ul class="navbar-nav justify-content-center w-100 bg-dark px-3">
    <li class="nav-item active">
      <a class="nav-link" href="/" style="color: white !important;">Blogs</a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="/about" style="color: white !important;">About</a>
    </li> 
    <li class="nav-item active">
      <a class="nav-link" href="/subscribe" style="color: white !important;">Subscribe</a>
    </li>
  </ul>
</div>
</nav>
</div>

app/templates/subscribe.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}
{% block content %}
<div class="container">
  <div class="form-area">
  <form action="/subscribe" method="post">
    {{subscribe_form.hidden_tag()}}
    <div class="form-outline mb-4">
    <label class="form-label" for="typeEmailX">Name</label>
    {{subscribe_form.username(type="text" ,id="typeEmailX",class="form-control form-control-lg")}}
    </div>
    <div class="form-outline mb-4">
      <label class="form-label" for="typeEmailX">Email</label>
      {{subscribe_form.email(type="email" ,id="typeEmailX",class="form-control form-control-lg")}}
      </div>
      <div>
        {{subscribe_form.submit(class="btn btn-outline-dark btn-lg px-5",type="submit")}}  
      </div>
  </form>
</div>
</div>
{% endblock %}